apiVersion : apps/v1
kind: Deployment
metadata:
  name: justinmannresumeservices 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: justinmannresumeservices
  template:
    metadata:
      labels:
        app: justinmannresumeservices 
    spec:
      containers:
        - name: justinmannresumeservices 
          image: jemacr.azurecr.io/justinmannresumeservices
          ports:
          - containerPort: 80